baserowImage: docker.pkg.github.com/hasadna/datacity-baserow/server:a0ce72140d92ac0abfe0ac7a6eb7310a37702af6
ckanDgpServerImage: docker.pkg.github.com/hasadna/datacity-ckan-dgp/server:daf0a69a2cc64272bfdf5d0c42d8d1fce8a6a94c
dgpAppDbImage: akariv/dgp-app-db@sha256:8ebf03009fb6c6e42308c2579b4ac2d979325a492fffd5942af0de3fc709ce28
dgpAppImage: docker.pkg.github.com/hasadna/datacity-dgp-importer/server:37184a42c327c304c08b4e5c764aceea2317dcbb
mapaliImage: docker.pkg.github.com/hasadna/datacity-mapali/server:1d3d0ef4fa350d85ead898ad2084e71488d5e94f
