adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:b3f990927d28cc4fa637084bd0bf7984181d6ccf
appImage: ghcr.io/whiletrue-industries/mapathataf-app:b3f990927d28cc4fa637084bd0bf7984181d6ccf
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:b3f990927d28cc4fa637084bd0bf7984181d6ccf
