adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:ffa67fd853c94ed462bae528dfe5cf2a06027d27
appImage: ghcr.io/whiletrue-industries/mapathataf-app:ffa67fd853c94ed462bae528dfe5cf2a06027d27
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:ffa67fd853c94ed462bae528dfe5cf2a06027d27
