adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:1889e44d35aa752209216edfd773b288a9bf586f
appImage: ghcr.io/whiletrue-industries/mapathataf-app:1889e44d35aa752209216edfd773b288a9bf586f
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:1889e44d35aa752209216edfd773b288a9bf586f
