adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:f71b20ae18104ac3e5b3cf7bbc44071a6346a9ea
appImage: ghcr.io/whiletrue-industries/mapathataf-app:f71b20ae18104ac3e5b3cf7bbc44071a6346a9ea
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:f71b20ae18104ac3e5b3cf7bbc44071a6346a9ea
