adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:45afc8f4a3f3551a35dd5ec2bba6331c3d8d8573
appImage: ghcr.io/whiletrue-industries/mapathataf-app:45afc8f4a3f3551a35dd5ec2bba6331c3d8d8573
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:45afc8f4a3f3551a35dd5ec2bba6331c3d8d8573
