adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:063678c9da9c4ece9cbadcc972322adf0750774f
appImage: ghcr.io/whiletrue-industries/mapathataf-app:063678c9da9c4ece9cbadcc972322adf0750774f
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:063678c9da9c4ece9cbadcc972322adf0750774f
