adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:869077e829f0669af7243c666a5683909dd8d2d0
appImage: ghcr.io/whiletrue-industries/mapathataf-app:869077e829f0669af7243c666a5683909dd8d2d0
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:869077e829f0669af7243c666a5683909dd8d2d0
