adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:7ec9b2c75314adafa2587e5779651268df0dd232
appImage: ghcr.io/whiletrue-industries/mapathataf-app:7ec9b2c75314adafa2587e5779651268df0dd232
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:7ec9b2c75314adafa2587e5779651268df0dd232
