adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:5d680c93733354d858f27adb3b508aece237e99a
appImage: ghcr.io/whiletrue-industries/mapathataf-app:5d680c93733354d858f27adb3b508aece237e99a
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:5d680c93733354d858f27adb3b508aece237e99a
