adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:e61b0d297e5e3cff978e1c18a5cb07929a2e24dc
appImage: ghcr.io/whiletrue-industries/mapathataf-app:e61b0d297e5e3cff978e1c18a5cb07929a2e24dc
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:e61b0d297e5e3cff978e1c18a5cb07929a2e24dc
