adminImage: ghcr.io/whiletrue-industries/mapathataf-admin:5a8640784ddafb4c243cb3ca9169a0e3ed92dde4
appImage: ghcr.io/whiletrue-industries/mapathataf-app:5a8640784ddafb4c243cb3ca9169a0e3ed92dde4
landingImage: ghcr.io/whiletrue-industries/mapathataf-landing:5a8640784ddafb4c243cb3ca9169a0e3ed92dde4
