backendImage: ghcr.io/hasadna/open-bus-backend/open-bus-backend:8486e82dd30dcaa887d347899c32c95d96a24435
mapSearchImage: ghcr.io/hasadna/open-bus-map-search/open-bus-map-search:b90dbbab62df05a7ce657f0c3cbc62277550b58e
pipelinesImage: ghcr.io/hasadna/open-bus-pipelines/open-bus-pipelines:6504554329823a625d0f497afaca7058cb191505
siriEtlImage: docker.pkg.github.com/hasadna/open-bus-siri-etl/open-bus-siri-etl:a9aa796fcc3fc0502838b1f0a43dae88eb153aba
siriRequesterImage: docker.pkg.github.com/hasadna/open-bus-siri-requester/open-bus-siri-requester:ed5ed1f76b65394d15570b6b5e637b205f754369
siriRequesterNginxImage: docker.pkg.github.com/hasadna/open-bus-siri-requester/open-bus-siri-requester-nginx:ed5ed1f76b65394d15570b6b5e637b205f754369
strideApiImage: ghcr.io/hasadna/open-bus-stride-api/open-bus-stride-api:46feea482194b0b4f0579cae974a516e182ef8e3
strideDbAppImage: ghcr.io/hasadna/open-bus-stride-db/open-bus-stride-db:39d4aa3ed3ac36e216a7ecba88f4bfdcb0cbf319
