backendImage: ghcr.io/hasadna/open-bus-backend/open-bus-backend:3efc7946818955b5f5b94a1423438c24d99a66da
mapSearchImage: ghcr.io/hasadna/open-bus-map-search/open-bus-map-search:c6ab416281fcf0d5f0d8c478760410e59c08942e
pipelinesImage: ghcr.io/hasadna/open-bus-pipelines/open-bus-pipelines:745eba437990893ec5c28a8a0a4f31f29c562829
ridesHistoryImage: ghcr.io/hasadna/open-bus-rides-history:0e3f80e056ec3d08c19e913f8764490a8347cb13
siriEtlImage: docker.pkg.github.com/hasadna/open-bus-siri-etl/open-bus-siri-etl:3f1a0c70f024e93a882ebe36f3f42ffb2bca7818
siriRequesterImage: docker.pkg.github.com/hasadna/open-bus-siri-requester/open-bus-siri-requester:1e344943c341176a6b97b0456cba5474392aaeeb
siriRequesterNginxImage: docker.pkg.github.com/hasadna/open-bus-siri-requester/open-bus-siri-requester-nginx:1e344943c341176a6b97b0456cba5474392aaeeb
strideApiImage: ghcr.io/hasadna/open-bus-stride-api/open-bus-stride-api:b8c5f7cdc5ca514ac4648f1c805c564ce925c34a
strideDbAppImage: ghcr.io/hasadna/open-bus-stride-db/open-bus-stride-db:058e5c9bc9ee6566fdd3ec3229b876dfc24852d3
