backendImage: ghcr.io/hasadna/open-bus-backend/open-bus-backend:13806a37f3733f1b6182bd4fee76520922817365
mapSearchImage: ghcr.io/hasadna/open-bus-map-search/open-bus-map-search:f738d2dfc6506906dc3a280aa8e526cbcf776d14
pipelinesImage: ghcr.io/hasadna/open-bus-pipelines/open-bus-pipelines:745eba437990893ec5c28a8a0a4f31f29c562829
ridesHistoryImage: ghcr.io/hasadna/open-bus-rides-history:0e3f80e056ec3d08c19e913f8764490a8347cb13
siriEtlImage: docker.pkg.github.com/hasadna/open-bus-siri-etl/open-bus-siri-etl:3f1a0c70f024e93a882ebe36f3f42ffb2bca7818
siriRequesterImage: docker.pkg.github.com/hasadna/open-bus-siri-requester/open-bus-siri-requester:1e344943c341176a6b97b0456cba5474392aaeeb
siriRequesterNginxImage: docker.pkg.github.com/hasadna/open-bus-siri-requester/open-bus-siri-requester-nginx:1e344943c341176a6b97b0456cba5474392aaeeb
strideApiImage: ghcr.io/hasadna/open-bus-stride-api/open-bus-stride-api:f2d4fa609b8a0b4607f9b72aa4cd7bc143334baa
strideDbAppImage: ghcr.io/hasadna/open-bus-stride-db/open-bus-stride-db:058e5c9bc9ee6566fdd3ec3229b876dfc24852d3
