anyway:
  anywayReportsImage: docker.pkg.github.com/hasadna/anyway-reports/anyway-reports:sha-b456d8b
  dbBackupImage: docker.pkg.github.com/hasadna/anyway/db_backup:sha-ac133ae
  dbImage: docker.pkg.github.com/hasadna/anyway/db:sha-ac133ae
  image: docker.pkg.github.com/hasadna/anyway/anyway:sha-ac133ae
  nginxImage: docker.pkg.github.com/hasadna/anyway/nginx:sha-ac133ae
  productionImage: uumpa/anyway:ef99d85b586a94d9e3b98a3e7dad195334318311
avidcovider:
  pipelinesImage: docker.pkg.github.com/hasadna/avid-covider-pipelines/pipelines:a32a5293d45c588859b28e8ecebcf4c7d1180cef
datacity:
  ckanDgpServerImage: docker.pkg.github.com/hasadna/datacity-ckan-dgp/server:2d56176315ed8c846e361e6839b11795ed34483a
  dgpAppDb: akariv/dgp-app-db@sha256:8ebf03009fb6c6e42308c2579b4ac2d979325a492fffd5942af0de3fc709ce28
  dgpAppImage: hasadna/datacity-dgp-importer@sha256:ed5062ef16b0b691fdf35eec889fda63f463dda710d5ac34397327575f58d2a2
mysadna:
  image: uumpa/hasadna-mysadna:c0a681d5a0c68ada76b6d68fce1c2115224790a9
odata:
  ckanImage: orihoch/odata-ckan:c225ad3f46df1a9e4ff0399ac135aa882ba851b7
oknesset:
  DataBackendImage: uumpa/knesset-data-backend:bc03d3c1830a856d6bbacf4b2481d83dd1f836c6
  WebUiImage: uumpa/knesset-data-web-ui:94b6de1cc89ae20647e35aa606c3c9b95e81dbe6
openpension:
  client:
    image: hasadna/open-pension-client:6dc1b88581df71c8aa98df79a666f1fc9ef9293f
  server:
    image: uumpa/hasadna-openpension:server-c72f525ec4d7de2e4337c0a7b0b1f6f8d357b72f
