anyway:
  airflowImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:v0.0.24
  airflowImageDev: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:7e37f6014f05de3d08fe755154e094888d9170e3
  anywayReportsImage: docker.pkg.github.com/hasadna/anyway-reports/anyway-reports:sha-b456d8b
  dbBackupImage: docker.pkg.github.com/hasadna/anyway/db_backup:sha-03ab35f
  dbImage: docker.pkg.github.com/hasadna/anyway/db:sha-03ab35f
  etlImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl:55a7c1ddb4610b2f75f88db8615f373b62c9f226
  etlNginxImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:v0.0.24
  etlNginxImageDev: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:7e37f6014f05de3d08fe755154e094888d9170e3
  image: docker.pkg.github.com/hasadna/anyway/anyway:sha-03ab35f
  imageDev: docker.pkg.github.com/hasadna/anyway/anyway:sha-e243854
  nginxImage: docker.pkg.github.com/hasadna/anyway/nginx:sha-03ab35f
  nginxImageDev: docker.pkg.github.com/hasadna/anyway/nginx:sha-e243854
avidcovider:
  pipelinesImage: docker.pkg.github.com/hasadna/avid-covider-pipelines/pipelines:a32a5293d45c588859b28e8ecebcf4c7d1180cef
datacity:
  ckanDgpServerImage: docker.pkg.github.com/hasadna/datacity-ckan-dgp/server:4a61be492e5c72e56d3aa9caadee5315cd48f90b
  dgpAppDbImage: akariv/dgp-app-db@sha256:8ebf03009fb6c6e42308c2579b4ac2d979325a492fffd5942af0de3fc709ce28
  dgpAppImage: docker.pkg.github.com/hasadna/datacity-dgp-importer/server:381ec3bb83fcb9336dc0633781b8258f8a036b39
mysadna:
  image: uumpa/hasadna-mysadna:c0a681d5a0c68ada76b6d68fce1c2115224790a9
odata:
  ckanImage: ghcr.io/orihoch/data4dappl/odata-ckan:a00ae4862a3a92d51334aa4e2d441e20bbf368f9
oknesset:
  DataBackendImage: uumpa/knesset-data-backend:bc03d3c1830a856d6bbacf4b2481d83dd1f836c6
  WebUiImage: uumpa/knesset-data-web-ui:94b6de1cc89ae20647e35aa606c3c9b95e81dbe6
openbus:
  pipelinesImage: docker.pkg.github.com/hasadna/open-bus-pipelines/open-bus-pipelines:f5afb460577055a02dd6d6b40abd84e4e4ac1136
  siriEtlImage: docker.pkg.github.com/hasadna/open-bus-siri-etl/open-bus-siri-etl:593e12d84b9792b1a5b6ddbd9e61f0bd240d4801
  siriRequesterImage: docker.pkg.github.com/hasadna/open-bus-siri-requester/open-bus-siri-requester:d13ad8bf536ac9aa9bfdf456bce2fb9b3f5f4d91
  siriRequesterNginxImage: docker.pkg.github.com/hasadna/open-bus-siri-requester/open-bus-siri-requester-nginx:d13ad8bf536ac9aa9bfdf456bce2fb9b3f5f4d91
  strideApiImage: ghcr.io/hasadna/open-bus-stride-api/open-bus-stride-api:898b9f78472130a3b6d2fddf2cecf4a562997edf
  strideDbAppImage: docker.pkg.github.com/hasadna/open-bus-stride-db/open-bus-stride-db:1cfde309910bf0c8d45802152db24d2f43fecee2
openpension:
  client:
    image: hasadna/open-pension-client:1f8f83e2a8e61e0928e4b5f499475f8e675265bd
  server:
    image: uumpa/hasadna-openpension:server-c72f525ec4d7de2e4337c0a7b0b1f6f8d357b72f
