anyway:
  image: uumpa/anyway:267f7419d02e00e6e74e9e57e2a217cf33b7d57c
  productionImage: uumpa/anyway:ef99d85b586a94d9e3b98a3e7dad195334318311
mysadna:
  image: uumpa/hasadna-mysadna:c0a681d5a0c68ada76b6d68fce1c2115224790a9
odata:
  ckanImage: orihoch/odata-ckan:e921261f0a849cf5887208424e9162b97b4e3fe2
oknesset:
  DataBackendImage: uumpa/knesset-data-backend:bc03d3c1830a856d6bbacf4b2481d83dd1f836c6
  WebUiImage: uumpa/knesset-data-web-ui:0cf83a828cefb42684bb562e01ddc3e15ca2b91c
