anyway:
  image: uumpa/anyway:testing-k8s-continuous-deployment
  productionImage: uumpa/anyway:testing-k8s-continuous-deployment
odata:
  ckanImage: orihoch/odata-ckan:4bd05adc9c124409537e47c8f18d1bcf2b0aa5b1
