{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcesaverproxy
spec:
  selector:
    matchLabels:
      app: resourcesaverproxy
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: resourcesaverproxy
    spec:
      terminationGracePeriodSeconds: 5
      automountServiceAccountToken: false
      containers:
      - name: web
        image: {{ .Values.image | quote }}
        command:
        - bash
        - "-c"
        - |
          gcloud auth activate-service-account --key-file=/etc/rsp/service_account.json &&\
          exec gunicorn -b 0.0.0.0:5000 -w 2 resourcesaverproxy.web:app
        resources: {{ .Values.webResources }}
        env:
        - name: RSP_RUNTIME_DATA
          value: /var/run/resourcesaverproxy
        - name: RSP_CONFIG
          value: /etc/rsp/config.yaml
        volumeMounts:
        - name: runtimedata
          mountPath: /var/run/resourcesaverproxy
        - name: config
          mountPath: /etc/rsp
      - name: daemon
        image: {{ .Values.image | quote }}
        command:
          - bash
          - "-c"
          - |
            gcloud auth activate-service-account --key-file=/etc/rsp/service_account.json &&\
            exec rsp start-deactivation-daemon
        resources: {{ .Values.daemonResources }}
        env:
        - name: RSP_RUNTIME_DATA
          value: /var/run/resourcesaverproxy
        - name: RSP_CONFIG
          value: /etc/rsp/config.yaml
        volumeMounts:
        - name: runtimedata
          mountPath: /var/run/resourcesaverproxy
        - name: config
          mountPath: /etc/rsp
      volumes:
      - name: runtimedata
        {{ if and .Values.nfsServer .Values.nfsPath }}
        nfs:
          server: {{ .Values.nfsServer | quote }}
          path: {{ $.Values.nfsPath | quote }}
        {{ else }}
        emptyDir: {}
        {{ end }}
      - name: config
        secret:
          # SEE https://github.com/OriHoch/ResourceSaverProxy
          secretName: resourcesaverproxy
{{ end }}
