apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-db
spec:
  selector:
    matchLabels:
      app: airflow-db
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow-db
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: db
        image: {{ .Values.airflowDb.image }}
        resources: {{ .Values.airflowDb.resources }}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom: {"secretKeyRef":{"name":"airflow-db", "key":"POSTGRES_PASSWORD"}}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: airflow_db
      volumes:
      - name: data
        nfs:
          server: {{ .Values.nfsServer | quote }}
          path: {{ .Values.airflowDb.nfsPath | quote }}
