apiVersion: apps/v1
kind: Deployment
metadata:
  name: siri-etl
spec:
  selector:
    matchLabels:
      app: siri-etl
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: siri-etl
    spec:
      terminationGracePeriodSeconds: 240
      containers:
        - name: process-new-snapshots
          image: {{ .Values.siriEtlImage }}
          resources: {{ .Values.siriEtlProcessNewSnapshotsResources }}
          args:
            - start-process-new-snapshots-daemon
          env:
            - name: OPEN_BUS_SIRI_STORAGE_ROOTPATH
              value: "/siri_requester_storage"
            - name: SQLALCHEMY_URL
              valueFrom: {"secretKeyRef":{"name":"db", "key":"SQLALCHEMY_URL"}}
            - name: DEBUG
              value: "yes"
          volumeMounts:
            - name: sirirequester
              mountPath: /siri_requester_storage
      volumes:
        - name: sirirequester
          nfs:
            server: {{ .Values.nfsServer | quote }}
            path: {{ .Values.siriRequesterNfsPath | quote }}
