apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-admin
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/cluster-admin
    plugin:
      name: uumpa
    repoURL: https://github.com/hasadna/hasadna-k8s.git
    targetRevision: add-atlantis
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
