migdar:
  enabled: true

traefik:
  # nfs needs an ip, be sure to update it in case of changes to the nfs service
  nfsServer: 10.23.253.67
  enableLoadBalancer: true
  # gcloud --project=hasadna-general compute addresses create hasadna-k8s-traefik --region=europe-west1
  # gcloud --project=hasadna-general compute addresses describe hasadna-k8s-traefik --region=europe-west1 | grep ^address:
  loadBalancerIP: 35.233.114.242

  letsencrypt:
    enabled: true
    acmeEmail: ori@uumpa.com
    dnsProvider: route53
    AWS_ACCESS_KEY_ID: AKIAIWMQWDTIM7IZS3EA
    AWS_REGION: "eu-west-1"
    awsSecretName: route53

  budgetkey:
    enabled: true
    frontendRule: "Host:next.obudget.org,data.obudget.org,socialmap.org.il,www.socialmap.org.il,kibana.obudget.org,www.obudget.org,obudget.org"
    backendUrl: "http://nginx.budgetkey:80"

  oknesset:
    enabled: true
    frontendRule: "Host:oknesset.org,www.oknesset.org,committees-next.oknesset.org,production.oknesset.org"
    backendUrl: "http://nginx.oknesset:80"
    acmeDomains: |
      [[acme.domains]]
        main = "production.oknesset.org"
      [[acme.domains]]
        main = "committees-next.oknesset.org"
      [[acme.domains]]
        main = "oknesset.org"
      [[acme.domains]]
        main = "www.oknesset.org"

  anyway:
    enabled: true
    frontendRule: "Host:test.anyway.co.il"
    backendUrl: "http://anyway.anyway:8000"
    acmeDomains: |
      [[acme.domains]]
        main = "test.anyway.co.il"

  anywayProduction:
    enabled: true
    frontendRule: "Host:production.anyway.co.il"
    backendUrl: "http://anyway.anyway-production:8000"
    acmeDomains: |
      [[acme.domains]]
        main = "production.anyway.co.il"

  odata:
    enabled: true
    frontendRule: "Host:www.odata.org.il,test-odata.oknesset.org,new.odata.org.il,odata.org.il"
    backendUrl: "http://ckan.odata:5000"
    canonicalDomainRedirect:
      matchDomains: new.odata.org.il|odata.org.il
      canonicalDomain: www.odata.org.il
