apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digital-forest-cards-site
  namespace: rook-ceph
  annotations:
{{/*    nginx.ingress.kubernetes.io/proxy-intercept-errors: "true"*/}}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/$ /digital-forest-cards-site/index.html break;
      rewrite ^/(.*)$ /digital-forest-cards-site/$1 break;
      proxy_intercept_errors on;
      error_page 403 = /index.html;
spec:
  rules:
  - host: cards.digital-forest.org.il
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: rook-ceph-rgw-hasadna
            port:
              number: 80
