{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  selector:
    matchLabels:
      app: strapi
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: strapi
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: strapi
        image: hasadna/reportit-cms
        ports:
        - containerPort: 1337
        resources: {{ .Values.strapi.resources }}
        volumeMounts:
        - name: data
          mountPath: /usr/src/api/reportit-cms
          subPath: reportit_strapi
        env:
        - name: DATABASE_HOST
          value: 'postgres'
      volumes:
      - name: data
        {{ if .Values.strapi.persistentVolumeClaimName }}
        persistentVolumeClaim:
          claimName: {{ .Values.strapi.persistentVolumeClaimName | quote }}
        {{ else if .Values.strapi.nfsServer }}
        nfs:
          server: {{ .Values.strapi.nfsServer | quote }}
          path: {{ .Values.strapi.nfsPath | quote }}
        {{ end }}
{{ end }}
