{{ if not .Values.redashInitialize }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adhoc-worker
spec:
  selector:
    matchLabels:
      app: adhoc-worker
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adhoc-worker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: adhoc-worker
        image: {{ .Values.redashImage | quote }}
        args: ["worker"]
        resources: {{ toYaml .Values.adhocWorker.resources | nindent 10 }}
        env:
        - name: QUEUES
          value: queries
        - name: WORKERS_COUNT
          value: {{ .Values.adhocWorker.WORKERS_COUNT | quote }}
        envFrom:
        - secretRef:
            name: redash
{{ end }}