resourcesaverproxy:
  enabled: true
  # repo: https://github.com/OriHoch/ResourceSaverProxy
  image: uumpa/resourcesaverproxy@sha256:f623e582fd3d74d15f97bc4c8e0d7b8765ffca696af7b093a89e642a037d3131
  webResources: '{"requests": {"cpu": "100m", "memory": "200Mi"}, "limits": {"memory": "600Mi"}}'
  daemonResources: '{"requests": {"cpu": "100m", "memory": "200Mi"}, "limits": {"memory": "600Mi"}}'
  nfsServer: "172.16.0.9"
  nfsPath: "/resourcesaver/proxy/runtime"
  ingresses:
    - name: web
      ssl: true
      rules:
        - host: resourcesaverproxy.hasadna.org.il
          serviceName: resourcesaverproxy
          servicePort: 5000
