{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: importer
spec:
  selector:
    matchLabels:
      app: importer
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: importer
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: importer
        image: {{ .Values.dgpAppImage | default "hasadna/datacity-dgp-importer" | quote }}
        resources: {"requests": {"cpu": "247m", "memory": "1953Mi"}, "limits": {"cpu": "350m", "memory": "3000Mi"}}
        ports:
        - containerPort: 5000
        env:
        - name: EXTERNAL_ADDRESS
          value: https://app.datacity.org.il
        - name: AIRFLOW__CORE__PARALLELISM
          value: "1"
        - name: AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL
          value: "60"
        - name: AIRFLOW__CORE__EXECUTOR
          value: SequentialExecutor
        - name: DATABASE_URL
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"AUTH_DATABASE_URL"}}
        - name: GOOGLE_MAPS_API_KEY
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"GOOGLE_MAPS_API_KEY"}}
        - name: ETLS_DATABASE_URL
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"ETLS_DATABASE_URL"}}
        - name: DATASETS_DATABASE_URL
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"DATASETS_DATABASE_URL"}}
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"AIRFLOW__CORE__SQL_ALCHEMY_CONN"}}
        - name: PUBLIC_KEY
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"PUBLIC_KEY"}}
        - name: PRIVATE_KEY
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"PRIVATE_KEY"}}
        - name: GITHUB_KEY
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"GITHUB_KEY"}}
        - name: GITHUB_SECRET
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"GITHUB_SECRET"}}
        - name: BUCKET_NAME
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"BUCKET_NAME"}}
        - name: AWS_ACCESS_KEY_ID
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"AWS_ACCESS_KEY_ID"}}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"AWS_SECRET_ACCESS_KEY"}}
        - name: AWS_REGION
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"AWS_REGION"}}
        - name: S3_ENDPOINT_URL
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"S3_ENDPOINT_URL"}}
{{ end }}
