{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: server
        image: {{ .Values.server.image }}
        resources: {{ .Values.server.resources }}
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: DEV
        - name: POSTGRES_PASSWORD
          valueFrom: {"secretKeyRef":{"name":"db", "key":"POSTGRES_PASSWORD"}}
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_DB
          value: openpension
        - name: DEBUG
          value: "False"
        - name: POSTGRES_USER
          valueFrom: {"secretKeyRef":{"name":"db", "key":"POSTGRES_USER"}}
        - name: SECRET_KEY
          valueFrom:  {"secretKeyRef":{"name":"server", "key":"SECRET_KEY"}}
        {{ if .Values.initialize }}
        - name: INITIALIZE
          value: "yes"
        {{ end }}
        command: ["/bin/sh"]
        args: ["entrypoint.sh"]
{{ end }}
