enabled: true
enableSecondaries: false
secondaryReplicas: 0
nginxForwardedHost: "dev.anyway.co.il"
nginxForwardedScheme: "https"
mountGoogleApplicationCredentialsSecret: true
mainResources: '{"requests": {"cpu": "25m", "memory": "684Mi"}, "limits": {"cpu": "78m", "memory": "1500Mi"}}'
secondariesResources: '{"requests": {"cpu": "25m", "memory": "933Mi"}, "limits": {"cpu": "78m", "memory": "1500Mi"}}'
dbResources: '{"requests": {"cpu": "25m", "memory": "2062Mi"}, "limits": {"cpu": "165m", "memory": "3500Mi"}}'
nginxResources: '{"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "500Mi"}}'
dbNfsServer: "~iac:hasadna_nfs1_internal_ip~"
dbNfsPath: "/anyway-dev/db"
DBDUMP_S3_FILE_PREFIX: ""
dbBackupEnabled: false
dbBackupResources: '{"requests": {"cpu": "25m", "memory": "700Mi"}, "limits": {"cpu": "165m", "memory": "1000Mi"}}'
dbBackupSchedule: "10 0 * * *"
enableLogs: false
# dbNodeSelector: hasadna-worker1
# dbHostPort: 28734
dbNodePort: 30735
dbRestoreFileName: "2021-10-10_anyway.pgdump"
useDevImages: true

reports:
  enabled: false
  replicas: 1
  resources: '{"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "500Mi"}}'

nfsServer: "~iac:hasadna_nfs1_internal_ip~"
enableAirflow: true
airflowDb:
  # pulled August 8, 2021
  image: "postgres:13@sha256:6647385dd9ae11aa2216bf55c54d126b0a85637b3cf4039ef24e3234113588e3"
  resources: {"requests": {"cpu": "50m", "memory": "300Mi"}, "limits": {"memory": "700Mi"}}
  nfsPath: "/anyway-dev/airflow-db"
airflowImageDev: "docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:latest"
airflowScheduler:
  resources: {"requests": {"cpu": "300m", "memory": "500Mi"}, "limits": {"memory": "1000Mi"}}
airflowWebserver:
  resources: {"requests": {"cpu": "50m", "memory": "300Mi"}, "limits": {"memory": "700Mi"}}
airflowHomeNfsPath: "/anyway-dev/airflow-home"
anywayEtlDataNfsPath: "/anyway-dev/etl-data"
etlNginxImageDev: "docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:latest"
etlNginxResources: {"requests": {"cpu": "50m", "memory": "100Mi"}, "limits": {"memory": "200Mi"}}
ANYWAY_ETL_BRANCH: "main"
ANYWAY_ETL_USE_LATEST_TAG: "no"
ANYWAY_KUBECTL_NAMESPACE: "anyway-dev"
AIRFLOW__SMTP__SMTP_MAIL_FROM: "Dev Airflow <dev-airflow@anyway.co.il>"
AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
AIRFLOW__WEBSERVER__BASE_URL: https://dev-airflow.anyway.co.il

ingresses:
  - name: nginx
    ssl: true
    rules:
      - host: dev.anyway.co.il
        serviceName: nginx
        servicePort: 80
      # - host: reports.anyway.co.il
      #   serviceName: reports
      #   servicePort: 80
  # - name: redirect
  #   ssl: true
  #   permanentRedirect: https://www.anyway.co.il
  #   rules:
  #     - host: anyway.co.il
  #       serviceName: nginx
  #       servicePort: 80
  #     - host: www.oway.org.il
  #       serviceName: nginx
  #       servicePort: 80
  #     - host: oway.org.il
  #       serviceName: nginx
  #       servicePort: 80
  - name: airflow
    ssl: true
    rules:
      - host: dev-airflow.anyway.co.il
        serviceName: airflow-webserver
        servicePort: 8080
  - name: airflow-data
    ssl: true
    rules:
      - host: dev-airflow-data.anyway.co.il
        serviceName: airflow-nginx
        servicePort: 80

vertical_pod_autoscalers:
- apiVersion: apps/v1
  kind: deployment
  name: anyway-main
# - apiVersion: apps/v1
#   kind: deployment
#   name: reports
# - apiVersion: apps/v1
#   kind: deployment
#   name: anyway-secondaries
- apiVersion: apps/v1
  kind: deployment
  name: db
- apiVersion: apps/v1
  kind: deployment
  name: nginx