#globalDisableAutoSync: true

projects:

  - name: openbus
    spec:
      destinations:
        - name: '*'
          namespace: openbus
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'
      orphanedResources:
        warn: true

  - name: betaknesset
    spec:
      destinations:
        - name: '*'
          namespace: betaknesset
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'
      orphanedResources:
        warn: true

  - name: odata
    spec:
      destinations:
        - name: '*'
          namespace: odata
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'
      orphanedResources:
        warn: true

  - name: datacity
    spec:
      destinations:
        - name: '*'
          namespace: datacity
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'
      orphanedResources:
        warn: true

  - name: openpension
    spec:
      destinations:
        - name: '*'
          namespace: openpension
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'
      orphanedResources:
        warn: true

  - name: reportit
    spec:
      destinations:
        - name: '*'
          namespace: reportit
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'
      orphanedResources:
        warn: true

  - name: migdar
    spec:
      destinations:
        - name: '*'
          namespace: migdar
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/migdar-k8s.git'
      orphanedResources:
        warn: true

  - name: oknesset
    spec:
      destinations:
        - name: '*'
          namespace: oknesset
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/OriHoch/knesset-data-k8s.git'
      orphanedResources:
        warn: true

  - name: budgetkey
    spec:
      destinations:
        - name: '*'
          namespace: budgetkey
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/OpenBudget/budgetkey-k8s.git'
      orphanedResources:
        warn: true

  - name: srm
    spec:
      destinations:
        - name: '*'
          namespace: srm-etl-production
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: srm-etl-staging
          server: 'https://kubernetes.default.svc'
        - name: 'datacity'
          namespace: srm-site-staging
          server: '*'
        - name: 'datacity'
          namespace: srm-site-production
          server: '*'
        - name: 'datacity'
          namespace: srm-e664cac9300c
          server: '*'
      sourceRepos:
        - 'https://github.com/whiletrue-industries/srm-devops.git'
      orphanedResources:
        warn: true

  - name: anyway
    spec:
      destinations:
        - name: '*'
          namespace: anyway
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: anyway-dev
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'

apps:

  - name: cluster-admin
    project: default
    destinationNamespace: default
    disableAutoSync: true
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/cluster-admin
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml

  - name: openbus
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/openbus
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml
      - values-hasadna-auto-updated.yaml

  - name: betaknesset
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/betaknesset
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml

  - name: odata
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/odata
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml
      - values-hasadna-auto-updated.yaml

  - name: datacity
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/datacity
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml
      - values-hasadna-auto-updated.yaml

  - name: openpension
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/openpension
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml

  - name: redash
    project: default
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/redash
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml

  - name: reportit
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/reportit
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml

  - name: resourcesaver
    project: default
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/resourcesaverproxy
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml

  - name: vault
    project: default
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/vault
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml

  - name: wordpress
    project: default
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/wordpress
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml

  - name: migdar
    source:
      repoURL: 'https://github.com/hasadna/migdar-k8s.git'
      targetRevision: master
      path: apps/migdar
    sourceVaultPluginHelmValueFiles:
      - values-global.yaml
      - values-hasadna.yaml
      - values-hasadna-auto-updated.yaml

  - name: oknesset-nginx
    project: oknesset
    destinationNamespace: oknesset
    source:
      repoURL: 'https://github.com/OriHoch/knesset-data-k8s.git'
      targetRevision: master
      path: apps/nginx
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml

  - name: oknesset-pipelines
    project: oknesset
    destinationNamespace: oknesset
    source:
      repoURL: 'https://github.com/OriHoch/knesset-data-k8s.git'
      targetRevision: master
      path: apps/pipelines
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml
      - values-hasadna-auto-updated.yaml

  - name: oknesset-publicdb
    project: oknesset
    destinationNamespace: oknesset
    source:
      repoURL: 'https://github.com/OriHoch/knesset-data-k8s.git'
      targetRevision: master
      path: apps/publicdb
    sourceVaultPluginHelmValueFiles:
      - values-hasadna.yaml

  - name: budgetkey
    source:
      repoURL: 'https://github.com/OpenBudget/budgetkey-k8s.git'
      targetRevision: master
      path: .
    sourceVaultPluginHelmValueFiles:
      - values-global.yaml
      - values-hasadna.yaml
      - values.auto-updated.yaml

  - name: srm-etl-production
    project: srm
    source:
      repoURL: 'https://github.com/whiletrue-industries/srm-devops.git'
      targetRevision: main
      path: helm/etl
    sourceVaultPluginHelmValueFiles:
      - values.yaml
      - values.auto-updated.yaml
      - values.production.yaml
      - values.auto-updated.production.yaml

  - name: srm-etl-staging
    project: srm
    source:
      repoURL: 'https://github.com/whiletrue-industries/srm-devops.git'
      targetRevision: main
      path: helm/etl
    sourceVaultPluginHelmValueFiles:
      - values.yaml
      - values.auto-updated.yaml
      - values.staging.yaml

  - name: srm-site-production
    project: srm
    destinationClusterName: datacity
    source:
      repoURL: 'https://github.com/whiletrue-industries/srm-devops.git'
      targetRevision: main
      path: helm/site
    sourceVaultPluginHelmValueFiles:
      - values.yaml
      - values.auto-updated.yaml
      - values.production.yaml
      - values.auto-updated.production.yaml

  - name: srm-site-staging
    project: srm
    destinationClusterName: datacity
    source:
      repoURL: 'https://github.com/whiletrue-industries/srm-devops.git'
      targetRevision: main
      path: helm/site
    sourceVaultPluginHelmValueFiles:
      - values.yaml
      - values.auto-updated.yaml
      - values.staging.yaml

  - name: srm-ckan-production-backups
    project: srm
    destinationNamespace: srm-e664cac9300c
    destinationClusterName: datacity
    source:
      repoURL: 'https://github.com/whiletrue-industries/srm-devops.git'
      targetRevision: main
      path: helm/ckan-backups
    sourceVaultPluginHelmValueFiles:
      - values.yaml

  - name: anyway-prod
    disableAutoSync: true
    project: anyway
    destinationNamespace: anyway
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/anyway
    sourceVaultPluginHelmValueFiles:
      - values-anyway-prod.yaml
      - values-anyway-auto-updated.yaml

  - name: anyway-dev
    disableAutoSync: true
    project: anyway
    destinationNamespace: anyway-dev
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/anyway
    sourceVaultPluginHelmValueFiles:
      - values-anyway-dev.yaml
      - values-anyway-auto-updated.yaml

  - name: argo-install
    disableAutoSync: true
    project: default
    destinationNamespace: argo
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/argo/manifests

  - name: argo
    disableAutoSync: true
    project: default
    destinationNamespace: argo
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/argo
    sourceVaultPluginHelmValueFiles:
      - values.yaml
