apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{ if .Values.ckanHostPort }}1{{ else }}{{ .Values.nginxReplicas | default "2" }}{{ end }}
  {{ if .Values.ckanHostPort }}
  strategy:
    type: Recreate
  {{ end }}
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        # update the pod on nginx-conf changes
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 1
      {{ if .Values.nginxNodeHostName }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nginxNodeHostName | quote }}
      {{ end }}
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          {{ if .Values.ckanHostPort }}
          hostPort: {{ .Values.ckanHostPort }}
          {{ end }}
        resources: {{ .Values.nginxResources }}
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: nginx-htpasswd
          mountPath: /etc/htpasswd
          readOnly: true
        - name: ckan-data
          mountPath: /var/lib/ckan
          subPath: ckan
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx
      - name: nginx-htpasswd
        {{ if .Values.nginxHtpasswdSecretName }}
        secret:
          secretName: {{ .Values.nginxHtpasswdSecretName }}
        {{ else }}
        emptyDir: {}
        {{ end }}
      - name: ckan-data
        {{ if .Values.hostPath }}
        hostPath:
          path: {{ .Values.hostPath | quote }}
          type: DirectoryOrCreate
        {{ else }}
        nfs:
          server: {{ .Values.ckanDataNfsServer | default "nfs" | quote }}
          path: "/"
        {{ end }}
